CREATE TABLE IF NOT EXISTS `zones` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `zones_classic` (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `locations` (
	`ID` VARCHAR(32) NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`zone` INT UNSIGNED NOT NULL,
	`lat` DOUBLE NOT NULL,
	`lng` DOUBLE NOT NULL,
	`map` TINYINT UNSIGNED NOT NULL DEFAULT 0,
	`enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `locations_classic` (
	`ID` VARCHAR(32) NOT NULL,
	`name` VARCHAR(100) NOT NULL,
	`zone` INT UNSIGNED NOT NULL,
	`lat` DOUBLE NOT NULL,
	`lng` DOUBLE NOT NULL,
	`enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `sessions` (
	`token` VARCHAR(36) NOT NULL,
	`currentID` VARCHAR(32) NOT NULL,
	`lives` TINYINT UNSIGNED NOT NULL DEFAULT 3,
	`updated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`gameMode` TINYINT UNSIGNED NOT NULL DEFAULT 1,
	`score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `guesses` (
	`token` VARCHAR(36) NOT NULL,
	`locationID` VARCHAR(32) NOT NULL,
	`distPct` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
	KEY `ID` (`token`),
	KEY `locationID` (`locationID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `scoreboard` (
	`ID` VARCHAR(36) NOT NULL,
	`score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`accuracy` DOUBLE NOT NULL DEFAULT 0,
	`name` VARCHAR(30) NOT NULL DEFAULT 'Unknown Player',
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `scoreboard_classic` (
	`ID` VARCHAR(36) NOT NULL,
	`score` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`accuracy` DOUBLE UNSIGNED NOT NULL DEFAULT 0,
	`name` VARCHAR(30) NOT NULL DEFAULT 'Unknown Player',
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
